// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldSpacing.cs" with this contents:
/*
namespace AppCode.Test.Data
{
  public partial class FieldSpacing
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Test.Data
{
  // This is a generated class for FieldSpacing (scope: EditUi)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldSpacing data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AnotherFieldBeforeGroup`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope EditUi.
  /// </remarks>
  public partial class FieldSpacing: AutoGenerated.ZAutoGenFieldSpacing
  {  }
}

namespace AppCode.Test.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'FieldSpacing' in scope 'EditUi'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldSpacing: Custom.Data.CustomItem
  {
    /// <summary>
    /// AnotherFieldBeforeGroup as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("AnotherFieldBeforeGroup", scrubHtml: true) etc.
    /// </summary>
    public string AnotherFieldBeforeGroup => _item.String("AnotherFieldBeforeGroup", fallback: "");

    /// <summary>
    /// Lib1 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Lib1")
    /// </summary>
    public string Lib1 => _item.Url("Lib1");

    /// <summary>
    /// Get the file object for Lib1 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile Lib1File => _item.File("Lib1");

    /// <summary>
    /// Get the folder object for Lib1.
    /// </summary>

    [JsonIgnore]
    public IFolder Lib1Folder => _item.Folder("Lib1");

    /// <summary>
    /// Lib2 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Lib2")
    /// </summary>
    public string Lib2 => _item.Url("Lib2");

    /// <summary>
    /// Get the file object for Lib2 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile Lib2File => _item.File("Lib2");

    /// <summary>
    /// Get the folder object for Lib2.
    /// </summary>

    [JsonIgnore]
    public IFolder Lib2Folder => _item.Folder("Lib2");

    /// <summary>
    /// LibWithHelp1 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LibWithHelp1")
    /// </summary>
    public string LibWithHelp1 => _item.Url("LibWithHelp1");

    /// <summary>
    /// Get the file object for LibWithHelp1 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibWithHelp1File => _item.File("LibWithHelp1");

    /// <summary>
    /// Get the folder object for LibWithHelp1.
    /// </summary>

    [JsonIgnore]
    public IFolder LibWithHelp1Folder => _item.Folder("LibWithHelp1");

    /// <summary>
    /// LibWithHelp2 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LibWithHelp2")
    /// </summary>
    public string LibWithHelp2 => _item.Url("LibWithHelp2");

    /// <summary>
    /// Get the file object for LibWithHelp2 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibWithHelp2File => _item.File("LibWithHelp2");

    /// <summary>
    /// Get the folder object for LibWithHelp2.
    /// </summary>

    [JsonIgnore]
    public IFolder LibWithHelp2Folder => _item.Folder("LibWithHelp2");

    /// <summary>
    /// Link1 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Link1")
    /// </summary>
    public string Link1 => _item.Url("Link1");

    /// <summary>
    /// Get the file object for Link1 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile Link1File => _item.File("Link1");

    /// <summary>
    /// Get the folder object for Link1.
    /// </summary>

    [JsonIgnore]
    public IFolder Link1Folder => _item.Folder("Link1");

    /// <summary>
    /// Link2 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Link2")
    /// </summary>
    public string Link2 => _item.Url("Link2");

    /// <summary>
    /// Get the file object for Link2 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile Link2File => _item.File("Link2");

    /// <summary>
    /// Get the folder object for Link2.
    /// </summary>

    [JsonIgnore]
    public IFolder Link2Folder => _item.Folder("Link2");

    /// <summary>
    /// LinkWithHelp1 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LinkWithHelp1")
    /// </summary>
    public string LinkWithHelp1 => _item.Url("LinkWithHelp1");

    /// <summary>
    /// Get the file object for LinkWithHelp1 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LinkWithHelp1File => _item.File("LinkWithHelp1");

    /// <summary>
    /// Get the folder object for LinkWithHelp1.
    /// </summary>

    [JsonIgnore]
    public IFolder LinkWithHelp1Folder => _item.Folder("LinkWithHelp1");

    /// <summary>
    /// LinkWithHelp2 as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LinkWithHelp2")
    /// </summary>
    public string LinkWithHelp2 => _item.Url("LinkWithHelp2");

    /// <summary>
    /// Get the file object for LinkWithHelp2 - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LinkWithHelp2File => _item.File("LinkWithHelp2");

    /// <summary>
    /// Get the folder object for LinkWithHelp2.
    /// </summary>

    [JsonIgnore]
    public IFolder LinkWithHelp2Folder => _item.Folder("LinkWithHelp2");

    /// <summary>
    /// Number1 as int. <br/>
    /// To get other types use methods such as .Decimal("Number1")
    /// </summary>
    public int Number1 => _item.Int("Number1");

    /// <summary>
    /// Number2 as int. <br/>
    /// To get other types use methods such as .Decimal("Number2")
    /// </summary>
    public int Number2 => _item.Int("Number2");

    /// <summary>
    /// Number3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Number3", scrubHtml: true) etc.
    /// </summary>
    public string Number3 => _item.String("Number3", fallback: "");

    /// <summary>
    /// NumberWithHelp1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NumberWithHelp1", scrubHtml: true) etc.
    /// </summary>
    public string NumberWithHelp1 => _item.String("NumberWithHelp1", fallback: "");

    /// <summary>
    /// NumberWithHelp2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NumberWithHelp2", scrubHtml: true) etc.
    /// </summary>
    public string NumberWithHelp2 => _item.String("NumberWithHelp2", fallback: "");

    /// <summary>
    /// NumberWithHelp3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NumberWithHelp3", scrubHtml: true) etc.
    /// </summary>
    public string NumberWithHelp3 => _item.String("NumberWithHelp3", fallback: "");

    /// <summary>
    /// OneLiner1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLiner1", scrubHtml: true) etc.
    /// </summary>
    public string OneLiner1 => _item.String("OneLiner1", fallback: "");

    /// <summary>
    /// OneLiner2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLiner2", scrubHtml: true) etc.
    /// </summary>
    public string OneLiner2 => _item.String("OneLiner2", fallback: "");

    /// <summary>
    /// OneLiner3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLiner3", scrubHtml: true) etc.
    /// </summary>
    public string OneLiner3 => _item.String("OneLiner3", fallback: "");

    /// <summary>
    /// OneLiner4 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLiner4", scrubHtml: true) etc.
    /// </summary>
    public string OneLiner4 => _item.String("OneLiner4", fallback: "");

    /// <summary>
    /// OneLinerWithHelp1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLinerWithHelp1", scrubHtml: true) etc.
    /// </summary>
    public string OneLinerWithHelp1 => _item.String("OneLinerWithHelp1", fallback: "");

    /// <summary>
    /// OneLinerWithHelp2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OneLinerWithHelp2", scrubHtml: true) etc.
    /// </summary>
    public string OneLinerWithHelp2 => _item.String("OneLinerWithHelp2", fallback: "");

    /// <summary>
    /// Picker1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Picker1", scrubHtml: true) etc.
    /// </summary>
    public string Picker1 => _item.String("Picker1", fallback: "");

    /// <summary>
    /// Picker2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Picker2", scrubHtml: true) etc.
    /// </summary>
    public string Picker2 => _item.String("Picker2", fallback: "");

    /// <summary>
    /// Picker3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Picker3", scrubHtml: true) etc.
    /// </summary>
    public string Picker3 => _item.String("Picker3", fallback: "");

    /// <summary>
    /// PickerWithHelp1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PickerWithHelp1", scrubHtml: true) etc.
    /// </summary>
    public string PickerWithHelp1 => _item.String("PickerWithHelp1", fallback: "");

    /// <summary>
    /// PickerWithHelp2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PickerWithHelp2", scrubHtml: true) etc.
    /// </summary>
    public string PickerWithHelp2 => _item.String("PickerWithHelp2", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// WysiwygNormal1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormal1", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormal1 => _item.String("WysiwygNormal1", fallback: "");

    /// <summary>
    /// WysiwygNormal2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormal2", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormal2 => _item.String("WysiwygNormal2", fallback: "");

    /// <summary>
    /// WysiwygNormal3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormal3", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormal3 => _item.String("WysiwygNormal3", fallback: "");

    /// <summary>
    /// WysiwygNormalWithHelp1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormalWithHelp1", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormalWithHelp1 => _item.String("WysiwygNormalWithHelp1", fallback: "");

    /// <summary>
    /// WysiwygNormalWithHelp2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormalWithHelp2", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormalWithHelp2 => _item.String("WysiwygNormalWithHelp2", fallback: "");

    /// <summary>
    /// WysiwygNormalWithHelp3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WysiwygNormalWithHelp3", scrubHtml: true) etc.
    /// </summary>
    public string WysiwygNormalWithHelp3 => _item.String("WysiwygNormalWithHelp3", fallback: "");
  }
}