// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RadminResources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RadminResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Extension Radmin/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for RadminResources 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RadminResources data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.ViewConfigModeLabel`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RadminResources: AutoGenerated.ZAutoGenRadminResources
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.RadminResources in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRadminResources: Custom.Data.CustomItem
  {
    /// <summary>
    /// ViewConfigModeLabel as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ViewConfigModeLabel", scrubHtml: true) etc.
    /// </summary>
    public string ViewConfigModeLabel => _item.String("ViewConfigModeLabel", fallback: "");
  }
}