// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AdamFieldsMetadataModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AdamFieldsMetadataModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for AdamFieldsMetadata 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AdamFieldsMetadata custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Category`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class AdamFieldsMetadataModel: AutoGenerated.ZAutoGenAdamFieldsMetadataModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AdamFieldsMetadataModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAdamFieldsMetadataModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Category as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Category", scrubHtml: true) etc.
    /// </summary>
    public string Category => _item.String("Category", fallback: "");

    /// <summary>
    /// Label as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Label", scrubHtml: true) etc.
    /// </summary>
    public string Label => _item.String("Label", fallback: "");
  }
}