// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AdamFields.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AdamFields
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-27 11:12:18Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for AdamFields
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AdamFields data. <br/>
  /// Generated 2024-02-27 11:12:18Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Album`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class AdamFields: AdamFieldsAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for AdamFields.
  /// </summary>
  public abstract class AdamFieldsAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Album as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Album")
    /// </summary>
    public string Album => _myItem.Url("Album");

    /// <summary>
    /// Get the file object for Album - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile AlbumFile => _myItem.File("AlbumFile");

    /// <summary>
    /// Get the folder object for Album.
    /// </summary>
    public IFolder AlbumFolder => _myItem.Folder("AlbumFolder");

    /// <summary>
    /// Document as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Document")
    /// </summary>
    public string Document => _myItem.Url("Document");

    /// <summary>
    /// Get the file object for Document - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile DocumentFile => _myItem.File("DocumentFile");

    /// <summary>
    /// Get the folder object for Document.
    /// </summary>
    public IFolder DocumentFolder => _myItem.Folder("DocumentFolder");

    /// <summary>
    /// Image as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Image")
    /// </summary>
    public string Image => _myItem.Url("Image");

    /// <summary>
    /// Get the file object for Image - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ImageFile => _myItem.File("ImageFile");

    /// <summary>
    /// Get the folder object for Image.
    /// </summary>
    public IFolder ImageFolder => _myItem.Folder("ImageFolder");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _myItem.String("Title", fallback: "");

    /// <summary>
    /// Url as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Url")
    /// </summary>
    public string Url => _myItem.Url("Url");

    /// <summary>
    /// Get the file object for Url - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile UrlFile => _myItem.File("UrlFile");

    /// <summary>
    /// Get the folder object for Url.
    /// </summary>
    public IFolder UrlFolder => _myItem.Folder("UrlFolder");
  }
}