// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AdamFieldsModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AdamFieldsModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated custom model class for AdamFields 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AdamFields custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Album`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class AdamFieldsModel: AutoGenerated.ZAutoGenAdamFieldsModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AdamFieldsModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAdamFieldsModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Album as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Album")
    /// </summary>
    public string Album => _item.Url("Album");

    /// <summary>
    /// Get the file object for Album - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile AlbumFile => _item.File("Album");

    /// <summary>
    /// Get the folder object for Album.
    /// </summary>

    [JsonIgnore]
    public IFolder AlbumFolder => _item.Folder("Album");

    /// <summary>
    /// Document as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Document")
    /// </summary>
    public string Document => _item.Url("Document");

    /// <summary>
    /// Get the file object for Document - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile DocumentFile => _item.File("Document");

    /// <summary>
    /// Get the folder object for Document.
    /// </summary>

    [JsonIgnore]
    public IFolder DocumentFolder => _item.Folder("Document");

    /// <summary>
    /// Image as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Image")
    /// </summary>
    public string Image => _item.Url("Image");

    /// <summary>
    /// Get the file object for Image - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile ImageFile => _item.File("Image");

    /// <summary>
    /// Get the folder object for Image.
    /// </summary>

    [JsonIgnore]
    public IFolder ImageFolder => _item.Folder("Image");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Url as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Url")
    /// </summary>
    public string Url => _item.Url("Url");

    /// <summary>
    /// Get the file object for Url - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile UrlFile => _item.File("Url");

    /// <summary>
    /// Get the folder object for Url.
    /// </summary>

    [JsonIgnore]
    public IFolder UrlFolder => _item.Folder("Url");
  }
}