// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppDataCreateUpdateDeleteModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppDataCreateUpdateDeleteModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated custom model class for AppDataCreateUpdateDelete 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppDataCreateUpdateDelete custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Boolean`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class AppDataCreateUpdateDeleteModel: AutoGenerated.ZAutoGenAppDataCreateUpdateDeleteModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AppDataCreateUpdateDeleteModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAppDataCreateUpdateDeleteModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Boolean as bool. <br/>
    /// To get nullable use .Get("Boolean") as bool?;
    /// </summary>
    public bool Boolean => _item.Bool("Boolean");

    /// <summary>
    /// BooleanTristate as bool. <br/>
    /// To get nullable use .Get("BooleanTristate") as bool?;
    /// </summary>
    public bool BooleanTristate => _item.Bool("BooleanTristate");

    /// <summary>
    /// Number as int. <br/>
    /// To get other types use methods such as .Decimal("Number")
    /// </summary>
    public int Number => _item.Int("Number");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// TodoImage as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("TodoImage")
    /// </summary>
    public string TodoImage => _item.Url("TodoImage");

    /// <summary>
    /// Get the file object for TodoImage - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile TodoImageFile => _item.File("TodoImage");

    /// <summary>
    /// Get the folder object for TodoImage.
    /// </summary>

    [JsonIgnore]
    public IFolder TodoImageFolder => _item.Folder("TodoImage");

    /// <summary>
    /// Wysiwyg as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Wysiwyg", scrubHtml: true) etc.
    /// </summary>
    public string Wysiwyg => _item.String("Wysiwyg", fallback: "");
  }
}