// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppDataCreateUpdateDelete.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppDataCreateUpdateDelete
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.03.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-03-04 13:17:54Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for AppDataCreateUpdateDelete 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppDataCreateUpdateDelete data. <br/>
  /// Generated 2024-03-04 13:17:54Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Boolean`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class AppDataCreateUpdateDelete: AutoGenerated.ZagAppDataCreateUpdateDelete
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AppDataCreateUpdateDelete in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagAppDataCreateUpdateDelete: Custom.Data.CustomItem
  {
    /// <summary>
    /// Boolean as bool. <br/>
    /// To get nullable use .Get("Boolean") as bool?;
    /// </summary>
    public bool Boolean => _item.Bool("Boolean");

    /// <summary>
    /// BooleanTristate as bool. <br/>
    /// To get nullable use .Get("BooleanTristate") as bool?;
    /// </summary>
    public bool BooleanTristate => _item.Bool("BooleanTristate");

    /// <summary>
    /// Number as int. <br/>
    /// To get other types use methods such as .Decimal("Number")
    /// </summary>
    public int Number => _item.Int("Number");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// TodoImage as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("TodoImage")
    /// </summary>
    public string TodoImage => _item.Url("TodoImage");

    /// <summary>
    /// Get the file object for TodoImage - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile TodoImageFile => _item.File("TodoImageFile");

    /// <summary>
    /// Get the folder object for TodoImage.
    /// </summary>
    public IFolder TodoImageFolder => _item.Folder("TodoImageFolder");

    /// <summary>
    /// Wysiwyg as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Wysiwyg", scrubHtml: true) etc.
    /// </summary>
    public string Wysiwyg => _item.String("Wysiwyg", fallback: "");
  }
}