// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppSettingsModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppSettingsModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System;

namespace AppCode.Data
{
  // This is a generated custom model class for AppSettings (scope: System.App)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppSettings custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.SettingForFormulaBool`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.App.
  /// </remarks>
  public partial class AppSettingsModel: AutoGenerated.ZAutoGenAppSettingsModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for System.App.AppSettingsModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAppSettingsModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// SettingForFormulaBool as bool. <br/>
    /// To get nullable use .Get("SettingForFormulaBool") as bool?;
    /// </summary>
    public bool SettingForFormulaBool => _item.Bool("SettingForFormulaBool");

    /// <summary>
    /// SettingForFormulaDate as DateTime.
    /// </summary>
    public DateTime SettingForFormulaDate => _item.DateTime("SettingForFormulaDate");

    /// <summary>
    /// SettingForFormulaText as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SettingForFormulaText", scrubHtml: true) etc.
    /// </summary>
    public string SettingForFormulaText => _item.String("SettingForFormulaText", fallback: "");
  }
}