// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AutoGenTestsModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AutoGenTestsModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;
using ToSic.Sxc.Cms.Data;
using ToSic.Sxc.Data;

namespace AppCode.Data
{
  // This is a generated custom model class for AutoGenTests 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AutoGenTests custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.EntityNotConfigured`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class AutoGenTestsModel: AutoGenerated.ZAutoGenAutoGenTestsModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AutoGenTestsModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAutoGenTestsModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// EntityNotConfigured as single item of ITypedItem.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. 
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public ITypedItem EntityNotConfigured => _entityNotConfigured ??= _item.Child("EntityNotConfigured");
    private ITypedItem _entityNotConfigured;

    /// <summary>
    /// EntityOfType as single item of Quotes.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type Quotes was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public Quotes EntityOfType => _entityOfType ??= _item.Child<Quotes>("EntityOfType");
    private Quotes _entityOfType;

    /// <summary>
    /// Gps as GPS Coordinates object with Latitude and Longitude.
    /// </summary>
    /// <remarks>
    /// This hides base property Gps.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new GpsCoordinates Gps => _item.Gps("Gps");

    /// <summary>
    /// NumberDecimal as decimal. <br/>
    /// To get other types use methods such as .Int("NumberDecimal")
    /// </summary>
    public decimal NumberDecimal => _item.Decimal("NumberDecimal");

    /// <summary>
    /// NumberInt as int. <br/>
    /// To get other types use methods such as .Decimal("NumberInt")
    /// </summary>
    public int NumberInt => _item.Int("NumberInt");

    /// <summary>
    /// NumberIntNeverConfigured as int. <br/>
    /// To get other types use methods such as .Decimal("NumberIntNeverConfigured")
    /// </summary>
    public int NumberIntNeverConfigured => _item.Int("NumberIntNeverConfigured");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}