// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ContentTypeEmpty.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ContentTypeEmpty
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for ContentTypeEmpty 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ContentTypeEmpty data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ContentTypeEmpty: AutoGenerated.ZAutoGenContentTypeEmpty
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ContentTypeEmpty in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenContentTypeEmpty: Custom.Data.CustomItem
  {  }
}