// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ContentTypeEmptyModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ContentTypeEmptyModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for ContentTypeEmpty 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ContentTypeEmpty custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class ContentTypeEmptyModel: AutoGenerated.ZAutoGenContentTypeEmptyModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ContentTypeEmptyModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenContentTypeEmptyModel: Custom.Data.CustomModel
  {  }
}