// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DataAdamModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DataAdamModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated custom model class for DataAdam 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DataAdam custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Library`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class DataAdamModel: AutoGenerated.ZAutoGenDataAdamModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.DataAdamModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenDataAdamModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Library as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Library")
    /// </summary>
    public string Library => _item.Url("Library");

    /// <summary>
    /// Get the file object for Library - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryFile => _item.File("Library");

    /// <summary>
    /// Get the folder object for Library.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryFolder => _item.Folder("Library");

    /// <summary>
    /// Single as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Single")
    /// </summary>
    public string Single => _item.Url("Single");

    /// <summary>
    /// Get the file object for Single - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile SingleFile => _item.File("Single");

    /// <summary>
    /// Get the folder object for Single.
    /// </summary>

    [JsonIgnore]
    public IFolder SingleFolder => _item.Folder("Single");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}