// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DataWithRelationshipChild.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DataWithRelationshipChild
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-27 11:12:18Z
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for DataWithRelationshipChild
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DataWithRelationshipChild data. <br/>
  /// Generated 2024-02-27 11:12:18Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Children`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class DataWithRelationshipChild: DataWithRelationshipChildAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for DataWithRelationshipChild.
  /// </summary>
  public abstract class DataWithRelationshipChildAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Children as list of DataWithRelationshipGrandChild.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DataWithRelationshipGrandChild was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DataWithRelationshipGrandChild> Children => _children ??= _myItem.Children<DataWithRelationshipGrandChild>("Children");
    private IEnumerable<DataWithRelationshipGrandChild> _children;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _myItem.String("Title", fallback: "");
  }
}