// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DataWithRelationshipParentModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DataWithRelationshipParentModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated custom model class for DataWithRelationshipParent 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DataWithRelationshipParent custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Child`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class DataWithRelationshipParentModel: AutoGenerated.ZAutoGenDataWithRelationshipParentModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.DataWithRelationshipParentModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenDataWithRelationshipParentModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Child as single item of DataWithRelationshipChild.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type DataWithRelationshipChild was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public DataWithRelationshipChild Child => _child ??= _item.Child<DataWithRelationshipChild>("Child");
    private DataWithRelationshipChild _child;

    /// <summary>
    /// Children as list of DataWithRelationshipChild.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DataWithRelationshipChild was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DataWithRelationshipChild> Children => _children ??= _item.Children<DataWithRelationshipChild>("Children");
    private IEnumerable<DataWithRelationshipChild> _children;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}