// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DateTimeConfigurable.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DateTimeConfigurable
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-29 21:35:48Z
namespace AppCode.Data
{
  // This is a generated class for DateTimeConfigurable
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DateTimeConfigurable data. <br/>
  /// Generated 2024-02-29 21:35:48Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.DesiredDate`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class DateTimeConfigurable: DateTimeConfigurableAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for DateTimeConfigurable.
  /// </summary>
  public abstract class DateTimeConfigurableAutoGenerated: Custom.Data.CustomItem
  {
    /// <summary>
    /// DesiredDate as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DesiredDate", scrubHtml: true) etc.
    /// </summary>
    public string DesiredDate => _item.String("DesiredDate", fallback: "");

    /// <summary>
    /// Hours as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Hours", scrubHtml: true) etc.
    /// </summary>
    public string Hours => _item.String("Hours", fallback: "");
  }
}