// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "EditEntityListFromPage.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class EditEntityListFromPage
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for EditEntityListFromPage 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// EditEntityListFromPage data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.EntitiesBasic`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class EditEntityListFromPage: AutoGenerated.ZAutoGenEditEntityListFromPage
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'EditEntityListFromPage' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenEditEntityListFromPage: Custom.Data.CustomItem
  {
    /// <summary>
    /// EntitiesBasic as list of DummyData1.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DummyData1 was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DummyData1> EntitiesBasic => _entitiesBasic ??= _item.Children<DummyData1>("EntitiesBasic");
    private IEnumerable<DummyData1> _entitiesBasic;

    /// <summary>
    /// EntitiesPickerMany as list of DummyData1.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DummyData1 was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DummyData1> EntitiesPickerMany => _entitiesPickerMany ??= _item.Children<DummyData1>("EntitiesPickerMany");
    private IEnumerable<DummyData1> _entitiesPickerMany;

    /// <summary>
    /// EntitiesPickerOne as list of DummyData2.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DummyData2 was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DummyData2> EntitiesPickerOne => _entitiesPickerOne ??= _item.Children<DummyData2>("EntitiesPickerOne");
    private IEnumerable<DummyData2> _entitiesPickerOne;

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}