// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldValueWysiwyg.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldValueWysiwyg
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-27 11:12:18Z
namespace AppCode.Data
{
  // This is a generated class for FieldValueWysiwyg
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldValueWysiwyg data. <br/>
  /// Generated 2024-02-27 11:12:18Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Contents`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldValueWysiwyg: FieldValueWysiwygAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FieldValueWysiwyg.
  /// </summary>
  public abstract class FieldValueWysiwygAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Contents as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Contents", scrubHtml: true) etc.
    /// </summary>
    public string Contents => _myItem.String("Contents", fallback: "");

    /// <summary>
    /// TestDescription as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestDescription", scrubHtml: true) etc.
    /// </summary>
    public string TestDescription => _myItem.String("TestDescription", fallback: "");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _myItem.String("TestId", fallback: "");
  }
}