// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldValueWysiwygModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldValueWysiwygModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for FieldValueWysiwyg 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldValueWysiwyg custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Contents`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldValueWysiwygModel: AutoGenerated.ZAutoGenFieldValueWysiwygModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldValueWysiwygModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldValueWysiwygModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Contents as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Contents", scrubHtml: true) etc.
    /// </summary>
    public string Contents => _item.String("Contents", fallback: "");

    /// <summary>
    /// TestDescription as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestDescription", scrubHtml: true) etc.
    /// </summary>
    public string TestDescription => _item.String("TestDescription", fallback: "");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");
  }
}