// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsBooleanModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsBooleanModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for FieldsBoolean 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsBoolean custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.LabelStandardFalse`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsBooleanModel: AutoGenerated.ZAutoGenFieldsBooleanModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsBooleanModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsBooleanModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// LabelStandardFalse as bool. <br/>
    /// To get nullable use .Get("LabelStandardFalse") as bool?;
    /// </summary>
    public bool LabelStandardFalse => _item.Bool("LabelStandardFalse");

    /// <summary>
    /// LabelStandardTrue as bool. <br/>
    /// To get nullable use .Get("LabelStandardTrue") as bool?;
    /// </summary>
    public bool LabelStandardTrue => _item.Bool("LabelStandardTrue");

    /// <summary>
    /// LabelTristateFalse as bool. <br/>
    /// To get nullable use .Get("LabelTristateFalse") as bool?;
    /// </summary>
    public bool LabelTristateFalse => _item.Bool("LabelTristateFalse");

    /// <summary>
    /// LabelTristateNull as bool. <br/>
    /// To get nullable use .Get("LabelTristateNull") as bool?;
    /// </summary>
    public bool LabelTristateNull => _item.Bool("LabelTristateNull");

    /// <summary>
    /// LabelTristateTrue as bool. <br/>
    /// To get nullable use .Get("LabelTristateTrue") as bool?;
    /// </summary>
    public bool LabelTristateTrue => _item.Bool("LabelTristateTrue");

    /// <summary>
    /// NoLabelFalse as bool. <br/>
    /// To get nullable use .Get("NoLabelFalse") as bool?;
    /// </summary>
    public bool NoLabelFalse => _item.Bool("NoLabelFalse");

    /// <summary>
    /// NoLabelNull as bool. <br/>
    /// To get nullable use .Get("NoLabelNull") as bool?;
    /// </summary>
    public bool NoLabelNull => _item.Bool("NoLabelNull");

    /// <summary>
    /// NoLabelTrue as bool. <br/>
    /// To get nullable use .Get("NoLabelTrue") as bool?;
    /// </summary>
    public bool NoLabelTrue => _item.Bool("NoLabelTrue");

    /// <summary>
    /// NotRevDefaultLabeled as bool. <br/>
    /// To get nullable use .Get("NotRevDefaultLabeled") as bool?;
    /// </summary>
    public bool NotRevDefaultLabeled => _item.Bool("NotRevDefaultLabeled");

    /// <summary>
    /// NotRevTristateLabeled as bool. <br/>
    /// To get nullable use .Get("NotRevTristateLabeled") as bool?;
    /// </summary>
    public bool NotRevTristateLabeled => _item.Bool("NotRevTristateLabeled");

    /// <summary>
    /// RevDefaultLabeled as bool. <br/>
    /// To get nullable use .Get("RevDefaultLabeled") as bool?;
    /// </summary>
    public bool RevDefaultLabeled => _item.Bool("RevDefaultLabeled");

    /// <summary>
    /// RevDefaultUnlabeled as bool. <br/>
    /// To get nullable use .Get("RevDefaultUnlabeled") as bool?;
    /// </summary>
    public bool RevDefaultUnlabeled => _item.Bool("RevDefaultUnlabeled");

    /// <summary>
    /// RevTristateLabeled as bool. <br/>
    /// To get nullable use .Get("RevTristateLabeled") as bool?;
    /// </summary>
    public bool RevTristateLabeled => _item.Bool("RevTristateLabeled");

    /// <summary>
    /// RevTristateUnlabeled as bool. <br/>
    /// To get nullable use .Get("RevTristateUnlabeled") as bool?;
    /// </summary>
    public bool RevTristateUnlabeled => _item.Bool("RevTristateUnlabeled");
  }
}