// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsStringUrlModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsStringUrlModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for FieldsStringUrl 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsStringUrl custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.AutoTitleSlashSubtitle`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsStringUrlModel: AutoGenerated.ZAutoGenFieldsStringUrlModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsStringUrlModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsStringUrlModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// AutoTitleSlashSubtitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("AutoTitleSlashSubtitle", scrubHtml: true) etc.
    /// </summary>
    public string AutoTitleSlashSubtitle => _item.String("AutoTitleSlashSubtitle", fallback: "");

    /// <summary>
    /// AutoTitleSubtitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("AutoTitleSubtitle", scrubHtml: true) etc.
    /// </summary>
    public string AutoTitleSubtitle => _item.String("AutoTitleSubtitle", fallback: "");

    /// <summary>
    /// ConfiguredNoSlash as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ConfiguredNoSlash", scrubHtml: true) etc.
    /// </summary>
    public string ConfiguredNoSlash => _item.String("ConfiguredNoSlash", fallback: "");

    /// <summary>
    /// ConfiguredWithSlash as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ConfiguredWithSlash", scrubHtml: true) etc.
    /// </summary>
    public string ConfiguredWithSlash => _item.String("ConfiguredWithSlash", fallback: "");

    /// <summary>
    /// Subtitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Subtitle", scrubHtml: true) etc.
    /// </summary>
    public string Subtitle => _item.String("Subtitle", fallback: "");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Unconfigured as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Unconfigured", scrubHtml: true) etc.
    /// </summary>
    public string Unconfigured => _item.String("Unconfigured", fallback: "");
  }
}