// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsHyperlink.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsHyperlink
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for FieldsHyperlink 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsHyperlink data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Library`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldsHyperlink: AutoGenerated.ZAutoGenFieldsHyperlink
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsHyperlink in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsHyperlink: Custom.Data.CustomItem
  {
    /// <summary>
    /// Library as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Library")
    /// </summary>
    public string Library => _item.Url("Library");

    /// <summary>
    /// Get the file object for Library - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryFile => _item.File("Library");

    /// <summary>
    /// Get the folder object for Library.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryFolder => _item.Folder("Library");

    /// <summary>
    /// LibraryJpgOnly as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LibraryJpgOnly")
    /// </summary>
    public string LibraryJpgOnly => _item.Url("LibraryJpgOnly");

    /// <summary>
    /// Get the file object for LibraryJpgOnly - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryJpgOnlyFile => _item.File("LibraryJpgOnly");

    /// <summary>
    /// Get the folder object for LibraryJpgOnly.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryJpgOnlyFolder => _item.Folder("LibraryJpgOnly");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Unconfigured as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Unconfigured")
    /// </summary>
    public string Unconfigured => _item.Url("Unconfigured");

    /// <summary>
    /// Get the file object for Unconfigured - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile UnconfiguredFile => _item.File("Unconfigured");

    /// <summary>
    /// Get the folder object for Unconfigured.
    /// </summary>

    [JsonIgnore]
    public IFolder UnconfiguredFolder => _item.Folder("Unconfigured");
  }
}