// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsBoolean.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsBoolean
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-27 11:12:18Z
namespace AppCode.Data
{
  // This is a generated class for FieldsBoolean
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsBoolean data. <br/>
  /// Generated 2024-02-27 11:12:18Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.LabelStandardFalse`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldsBoolean: FieldsBooleanAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FieldsBoolean.
  /// </summary>
  public abstract class FieldsBooleanAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// LabelStandardFalse as bool. <br/>
    /// To get nullable use .Get("LabelStandardFalse") as bool?;
    /// </summary>
    public bool LabelStandardFalse => _myItem.Bool("LabelStandardFalse");

    /// <summary>
    /// LabelStandardTrue as bool. <br/>
    /// To get nullable use .Get("LabelStandardTrue") as bool?;
    /// </summary>
    public bool LabelStandardTrue => _myItem.Bool("LabelStandardTrue");

    /// <summary>
    /// LabelTristateFalse as bool. <br/>
    /// To get nullable use .Get("LabelTristateFalse") as bool?;
    /// </summary>
    public bool LabelTristateFalse => _myItem.Bool("LabelTristateFalse");

    /// <summary>
    /// LabelTristateNull as bool. <br/>
    /// To get nullable use .Get("LabelTristateNull") as bool?;
    /// </summary>
    public bool LabelTristateNull => _myItem.Bool("LabelTristateNull");

    /// <summary>
    /// LabelTristateTrue as bool. <br/>
    /// To get nullable use .Get("LabelTristateTrue") as bool?;
    /// </summary>
    public bool LabelTristateTrue => _myItem.Bool("LabelTristateTrue");

    /// <summary>
    /// NoLabelFalse as bool. <br/>
    /// To get nullable use .Get("NoLabelFalse") as bool?;
    /// </summary>
    public bool NoLabelFalse => _myItem.Bool("NoLabelFalse");

    /// <summary>
    /// NoLabelNull as bool. <br/>
    /// To get nullable use .Get("NoLabelNull") as bool?;
    /// </summary>
    public bool NoLabelNull => _myItem.Bool("NoLabelNull");

    /// <summary>
    /// NoLabelTrue as bool. <br/>
    /// To get nullable use .Get("NoLabelTrue") as bool?;
    /// </summary>
    public bool NoLabelTrue => _myItem.Bool("NoLabelTrue");

    /// <summary>
    /// NotRevDefaultLabeled as bool. <br/>
    /// To get nullable use .Get("NotRevDefaultLabeled") as bool?;
    /// </summary>
    public bool NotRevDefaultLabeled => _myItem.Bool("NotRevDefaultLabeled");

    /// <summary>
    /// NotRevTristateLabeled as bool. <br/>
    /// To get nullable use .Get("NotRevTristateLabeled") as bool?;
    /// </summary>
    public bool NotRevTristateLabeled => _myItem.Bool("NotRevTristateLabeled");

    /// <summary>
    /// RevDefaultLabeled as bool. <br/>
    /// To get nullable use .Get("RevDefaultLabeled") as bool?;
    /// </summary>
    public bool RevDefaultLabeled => _myItem.Bool("RevDefaultLabeled");

    /// <summary>
    /// RevDefaultUnlabeled as bool. <br/>
    /// To get nullable use .Get("RevDefaultUnlabeled") as bool?;
    /// </summary>
    public bool RevDefaultUnlabeled => _myItem.Bool("RevDefaultUnlabeled");

    /// <summary>
    /// RevTristateLabeled as bool. <br/>
    /// To get nullable use .Get("RevTristateLabeled") as bool?;
    /// </summary>
    public bool RevTristateLabeled => _myItem.Bool("RevTristateLabeled");

    /// <summary>
    /// RevTristateUnlabeled as bool. <br/>
    /// To get nullable use .Get("RevTristateUnlabeled") as bool?;
    /// </summary>
    public bool RevTristateUnlabeled => _myItem.Bool("RevTristateUnlabeled");
  }
}