// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsStringJsonModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsStringJsonModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for FieldsStringJson 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsStringJson custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Json`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsStringJsonModel: AutoGenerated.ZAutoGenFieldsStringJsonModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsStringJsonModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsStringJsonModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Json as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Json", scrubHtml: true) etc.
    /// </summary>
    public string Json => _item.String("Json", fallback: "");
  }
}