// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsHyperlinkModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsHyperlinkModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated custom model class for FieldsHyperlink 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsHyperlink custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Library`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsHyperlinkModel: AutoGenerated.ZAutoGenFieldsHyperlinkModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsHyperlinkModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsHyperlinkModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Library as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Library")
    /// </summary>
    public string Library => _item.Url("Library");

    /// <summary>
    /// Get the file object for Library - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryFile => _item.File("Library");

    /// <summary>
    /// Get the folder object for Library.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryFolder => _item.Folder("Library");

    /// <summary>
    /// LibraryJpgOnly as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LibraryJpgOnly")
    /// </summary>
    public string LibraryJpgOnly => _item.Url("LibraryJpgOnly");

    /// <summary>
    /// Get the file object for LibraryJpgOnly - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryJpgOnlyFile => _item.File("LibraryJpgOnly");

    /// <summary>
    /// Get the folder object for LibraryJpgOnly.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryJpgOnlyFolder => _item.Folder("LibraryJpgOnly");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Unconfigured as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Unconfigured")
    /// </summary>
    public string Unconfigured => _item.Url("Unconfigured");

    /// <summary>
    /// Get the file object for Unconfigured - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile UnconfiguredFile => _item.File("Unconfigured");

    /// <summary>
    /// Get the folder object for Unconfigured.
    /// </summary>

    [JsonIgnore]
    public IFolder UnconfiguredFolder => _item.Folder("Unconfigured");
  }
}