// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsDateTime.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsDateTime
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-29 21:35:48Z
using System;

namespace AppCode.Data
{
  // This is a generated class for FieldsDateTime
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsDateTime data. <br/>
  /// Generated 2024-02-29 21:35:48Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.DateAndTime`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldsDateTime: FieldsDateTimeAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FieldsDateTime.
  /// </summary>
  public abstract class FieldsDateTimeAutoGenerated: Custom.Data.CustomItem
  {
    /// <summary>
    /// DateAndTime as DateTime.
    /// </summary>
    public DateTime DateAndTime => _item.DateTime("DateAndTime");

    /// <summary>
    /// DateOnly as DateTime.
    /// </summary>
    public DateTime DateOnly => _item.DateTime("DateOnly");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");
  }
}