// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsStringJson.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsStringJson
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for FieldsStringJson 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsStringJson data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Json`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldsStringJson: AutoGenerated.ZAutoGenFieldsStringJson
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsStringJson in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsStringJson: Custom.Data.CustomItem
  {
    /// <summary>
    /// Json as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Json", scrubHtml: true) etc.
    /// </summary>
    public string Json => _item.String("Json", fallback: "");
  }
}