// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsEmptyModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsEmptyModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for FieldsEmpty 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsEmpty custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.SomeField`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsEmptyModel: AutoGenerated.ZAutoGenFieldsEmptyModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsEmptyModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsEmptyModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// SomeField as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField", scrubHtml: true) etc.
    /// </summary>
    public string SomeField => _item.String("SomeField", fallback: "");

    /// <summary>
    /// SomeField2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField2", scrubHtml: true) etc.
    /// </summary>
    public string SomeField2 => _item.String("SomeField2", fallback: "");

    /// <summary>
    /// SomeField3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField3", scrubHtml: true) etc.
    /// </summary>
    public string SomeField3 => _item.String("SomeField3", fallback: "");

    /// <summary>
    /// SomeField4 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField4", scrubHtml: true) etc.
    /// </summary>
    public string SomeField4 => _item.String("SomeField4", fallback: "");

    /// <summary>
    /// SomeField5 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField5", scrubHtml: true) etc.
    /// </summary>
    public string SomeField5 => _item.String("SomeField5", fallback: "");
  }
}