// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsEmpty.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsEmpty
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-27 11:12:18Z
namespace AppCode.Data
{
  // This is a generated class for FieldsEmpty
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsEmpty data. <br/>
  /// Generated 2024-02-27 11:12:18Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.SomeField`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class FieldsEmpty: FieldsEmptyAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for FieldsEmpty.
  /// </summary>
  public abstract class FieldsEmptyAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// SomeField as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField", scrubHtml: true) etc.
    /// </summary>
    public string SomeField => _myItem.String("SomeField", fallback: "");

    /// <summary>
    /// SomeField2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField2", scrubHtml: true) etc.
    /// </summary>
    public string SomeField2 => _myItem.String("SomeField2", fallback: "");

    /// <summary>
    /// SomeField3 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField3", scrubHtml: true) etc.
    /// </summary>
    public string SomeField3 => _myItem.String("SomeField3", fallback: "");

    /// <summary>
    /// SomeField4 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField4", scrubHtml: true) etc.
    /// </summary>
    public string SomeField4 => _myItem.String("SomeField4", fallback: "");

    /// <summary>
    /// SomeField5 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SomeField5", scrubHtml: true) etc.
    /// </summary>
    public string SomeField5 => _myItem.String("SomeField5", fallback: "");
  }
}