// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsDateTimeModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsDateTimeModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System;

namespace AppCode.Data
{
  // This is a generated custom model class for FieldsDateTime 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsDateTime custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.DateAndTime`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsDateTimeModel: AutoGenerated.ZAutoGenFieldsDateTimeModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsDateTimeModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsDateTimeModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// DateAndTime as DateTime.
    /// </summary>
    public DateTime DateAndTime => _item.DateTime("DateAndTime");

    /// <summary>
    /// DateOnly as DateTime.
    /// </summary>
    public DateTime DateOnly => _item.DateTime("DateOnly");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}