// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "FieldsStringWysiwygInnerContentModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class FieldsStringWysiwygInnerContentModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;
using ToSic.Sxc.Data;

namespace AppCode.Data
{
  // This is a generated custom model class for FieldsStringWysiwygInnerContent 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// FieldsStringWysiwygInnerContent custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.InnerContent`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class FieldsStringWysiwygInnerContentModel: AutoGenerated.ZAutoGenFieldsStringWysiwygInnerContentModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.FieldsStringWysiwygInnerContentModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenFieldsStringWysiwygInnerContentModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// InnerContent as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("InnerContent", scrubHtml: true) etc.
    /// </summary>
    public string InnerContent => _item.String("InnerContent", fallback: "");

    /// <summary>
    /// InnerContentData as single item of ITypedItem.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. 
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public ITypedItem InnerContentData => _innerContentData ??= _item.Child("InnerContentData");
    private ITypedItem _innerContentData;

    /// <summary>
    /// NoInnerContent as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NoInnerContent", scrubHtml: true) etc.
    /// </summary>
    public string NoInnerContent => _item.String("NoInnerContent", fallback: "");
  }
}