// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ForPrefillTests.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ForPrefillTests
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.03.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-03-04 13:17:54Z
using System;
using System.Collections.Generic;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for ForPrefillTests 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ForPrefillTests data. <br/>
  /// Generated 2024-03-04 13:17:54Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.ALink`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ForPrefillTests: AutoGenerated.ZagForPrefillTests
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ForPrefillTests in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagForPrefillTests: Custom.Data.CustomItem
  {
    /// <summary>
    /// ALink as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("ALink")
    /// </summary>
    public string ALink => _item.Url("ALink");

    /// <summary>
    /// Get the file object for ALink - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ALinkFile => _item.File("ALinkFile");

    /// <summary>
    /// Get the folder object for ALink.
    /// </summary>
    public IFolder ALinkFolder => _item.Folder("ALinkFolder");

    /// <summary>
    /// ANumber as int. <br/>
    /// To get other types use methods such as .Decimal("ANumber")
    /// </summary>
    public int ANumber => _item.Int("ANumber");

    /// <summary>
    /// Date as DateTime.
    /// </summary>
    public DateTime Date => _item.DateTime("Date");

    /// <summary>
    /// Date2 as DateTime.
    /// </summary>
    public DateTime Date2 => _item.DateTime("Date2");

    /// <summary>
    /// Date3 as DateTime.
    /// </summary>
    public DateTime Date3 => _item.DateTime("Date3");

    /// <summary>
    /// IsSomething as bool. <br/>
    /// To get nullable use .Get("IsSomething") as bool?;
    /// </summary>
    public bool IsSomething => _item.Bool("IsSomething");

    /// <summary>
    /// ManyItems as list of ForPrefillTestsCategories.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type ForPrefillTestsCategories was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<ForPrefillTestsCategories> ManyItems => _manyItems ??= _item.Children<ForPrefillTestsCategories>("ManyItems");
    private IEnumerable<ForPrefillTestsCategories> _manyItems;

    /// <summary>
    /// SingleItem as single item of ForPrefillTestsCategories.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type ForPrefillTestsCategories was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public ForPrefillTestsCategories SingleItem => _singleItem ??= _item.Child<ForPrefillTestsCategories>("SingleItem");
    private ForPrefillTestsCategories _singleItem;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// WYSIWYG as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("WYSIWYG", scrubHtml: true) etc.
    /// </summary>
    public string WYSIWYG => _item.String("WYSIWYG", fallback: "");
  }
}