// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "LanguageTests.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class LanguageTests
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for LanguageTests 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// LanguageTests data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.LanguageCode`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class LanguageTests: AutoGenerated.ZAutoGenLanguageTests
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.LanguageTests in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenLanguageTests: Custom.Data.CustomItem
  {
    /// <summary>
    /// LanguageCode as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LanguageCode", scrubHtml: true) etc.
    /// </summary>
    public string LanguageCode => _item.String("LanguageCode", fallback: "");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}