// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "MultiLanguageTestsModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class MultiLanguageTestsModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for MultiLanguageTests 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// MultiLanguageTests custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.EmptyInDe`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class MultiLanguageTestsModel: AutoGenerated.ZAutoGenMultiLanguageTestsModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.MultiLanguageTestsModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenMultiLanguageTestsModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// EmptyInDe as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("EmptyInDe", scrubHtml: true) etc.
    /// </summary>
    public string EmptyInDe => _item.String("EmptyInDe", fallback: "");

    /// <summary>
    /// Number as int. <br/>
    /// To get other types use methods such as .Decimal("Number")
    /// </summary>
    public int Number => _item.Int("Number");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Wysiwyg as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Wysiwyg", scrubHtml: true) etc.
    /// </summary>
    public string Wysiwyg => _item.String("Wysiwyg", fallback: "");
  }
}