// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "QuotesModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class QuotesModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using ToSic.Eav.Models;

namespace AppCode.Data
{
  // This is a generated custom model class for QuotesModel 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// QuotesModel custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Author`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  [ModelSpecs(ContentType = "Quotes", Stream = "Quotes")]
  public partial class QuotesModelClassic: AutoGenerated.ZAutoGenQuotesModelClassic
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'QuotesModel' in data scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenQuotesModelClassic: ToSic.Eav.Models.ModelFromEntityClassic // Custom.Data.CustomModel
  {
    /// <summary>
    /// Author as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Author", scrubHtml: true) etc.
    /// </summary>
    public string Author => GetThis(fallback: "");

    /// <summary>
    /// Quote as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Quote", scrubHtml: true) etc.
    /// </summary>
    public string Quote => GetThis(fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => GetThis(fallback: "");
  }
}