// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RestTestAuthor.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RestTestAuthor
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated class for RestTestAuthor 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RestTestAuthor data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.IsMale`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RestTestAuthor: AutoGenerated.ZAutoGenRestTestAuthor
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RestTestAuthor' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRestTestAuthor: Custom.Data.CustomItem
  {
    /// <summary>
    /// IsMale as bool. <br/>
    /// To get nullable use .Get("IsMale") as bool?;
    /// </summary>
    public bool IsMale => _item.Bool("IsMale");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");
  }
}