// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RestTestBook.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RestTestBook
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System;
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for RestTestBook 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RestTestBook data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Authors`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RestTestBook: AutoGenerated.ZAutoGenRestTestBook
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RestTestBook' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRestTestBook: Custom.Data.CustomItem
  {
    /// <summary>
    /// Authors as list of RestTestAuthor.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type RestTestAuthor was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<RestTestAuthor> Authors => _authors ??= _item.Children<RestTestAuthor>("Authors");
    private IEnumerable<RestTestAuthor> _authors;

    /// <summary>
    /// ISBN as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ISBN", scrubHtml: true) etc.
    /// </summary>
    public string ISBN => _item.String("ISBN", fallback: "");

    /// <summary>
    /// Pages as int. <br/>
    /// To get other types use methods such as .Decimal("Pages")
    /// </summary>
    public int Pages => _item.Int("Pages");

    /// <summary>
    /// Published as DateTime.
    /// </summary>
    public DateTime Published => _item.DateTime("Published");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}