// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TempPickerShowingInheritedContentTypeModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TempPickerShowingInheritedContentTypeModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;
using ToSic.Sxc.Data;

namespace AppCode.Data
{
  // This is a generated custom model class for TempPickerShowingInheritedContentType 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TempPickerShowingInheritedContentType custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Fields`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class TempPickerShowingInheritedContentTypeModel: AutoGenerated.ZAutoGenTempPickerShowingInheritedContentTypeModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.TempPickerShowingInheritedContentTypeModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTempPickerShowingInheritedContentTypeModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Fields as single item of ITypedItem.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. 
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public ITypedItem Fields => _fields ??= _item.Child("Fields");
    private ITypedItem _fields;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}