// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TestPublishingModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TestPublishingModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for TestPublishing 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TestPublishing custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.TestId`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class TestPublishingModel: AutoGenerated.ZAutoGenTestPublishingModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.TestPublishingModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTestPublishingModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}