// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TestTemplateServiceModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TestTemplateServiceModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for TestTemplateService 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TestTemplateService custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Message`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class TestTemplateServiceModel: AutoGenerated.ZAutoGenTestTemplateServiceModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.TestTemplateServiceModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTestTemplateServiceModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Message as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Message", scrubHtml: true) etc.
    /// </summary>
    public string Message => _item.String("Message", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}