// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TestTemplateService.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TestTemplateService
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for TestTemplateService 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TestTemplateService data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Message`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class TestTemplateService: AutoGenerated.ZAutoGenTestTemplateService
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'TestTemplateService' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTestTemplateService: Custom.Data.CustomItem
  {
    /// <summary>
    /// Message as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Message", scrubHtml: true) etc.
    /// </summary>
    public string Message => _item.String("Message", fallback: "");

    /// <summary>
    /// Photo as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Photo")
    /// </summary>
    public string Photo => _item.Url("Photo");

    /// <summary>
    /// Get the file object for Photo - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile PhotoFile => _item.File("Photo");

    /// <summary>
    /// Get the folder object for Photo.
    /// </summary>

    [JsonIgnore]
    public IFolder PhotoFolder => _item.Folder("Photo");

    /// <summary>
    /// SomeBoolean as bool. <br/>
    /// To get nullable use .Get("SomeBoolean") as bool?;
    /// </summary>
    public bool SomeBoolean => _item.Bool("SomeBoolean");

    /// <summary>
    /// SomeNumber as int. <br/>
    /// To get other types use methods such as .Decimal("SomeNumber")
    /// </summary>
    public int SomeNumber => _item.Int("SomeNumber");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}