// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TestTemplateServiceData.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TestTemplateServiceData
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System;
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for TestTemplateServiceData 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TestTemplateServiceData data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Age`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class TestTemplateServiceData: AutoGenerated.ZAutoGenTestTemplateServiceData
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'TestTemplateServiceData' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTestTemplateServiceData: Custom.Data.CustomItem
  {
    /// <summary>
    /// Age as int. <br/>
    /// To get other types use methods such as .Decimal("Age")
    /// </summary>
    public int Age => _item.Int("Age");

    /// <summary>
    /// BetterPhoto as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("BetterPhoto")
    /// </summary>
    public string BetterPhoto => _item.Url("BetterPhoto");

    /// <summary>
    /// Get the file object for BetterPhoto - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile BetterPhotoFile => _item.File("BetterPhoto");

    /// <summary>
    /// Get the folder object for BetterPhoto.
    /// </summary>

    [JsonIgnore]
    public IFolder BetterPhotoFolder => _item.Folder("BetterPhoto");

    /// <summary>
    /// Birthday as DateTime.
    /// </summary>
    public DateTime Birthday => _item.DateTime("Birthday");

    /// <summary>
    /// OverrideSomeBoolean as bool. <br/>
    /// To get nullable use .Get("OverrideSomeBoolean") as bool?;
    /// </summary>
    public bool OverrideSomeBoolean => _item.Bool("OverrideSomeBoolean");

    /// <summary>
    /// OverrideSomeNumber as int. <br/>
    /// To get other types use methods such as .Decimal("OverrideSomeNumber")
    /// </summary>
    public int OverrideSomeNumber => _item.Int("OverrideSomeNumber");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}