// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ToolbarTestModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ToolbarTestModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated custom model class for ToolbarTest 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ToolbarTest custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Items`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class ToolbarTestModel: AutoGenerated.ZAutoGenToolbarTestModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ToolbarTestModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenToolbarTestModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Items as list of ToolbarTestItems.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type ToolbarTestItems was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<ToolbarTestItems> Items => _items ??= _item.Children<ToolbarTestItems>("Items");
    private IEnumerable<ToolbarTestItems> _items;

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}