// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ToolbarTest.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ToolbarTest
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.03.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-03-04 13:17:54Z
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for ToolbarTest 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ToolbarTest data. <br/>
  /// Generated 2024-03-04 13:17:54Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Items`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ToolbarTest: AutoGenerated.ZagToolbarTest
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ToolbarTest in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagToolbarTest: Custom.Data.CustomItem
  {
    /// <summary>
    /// Items as list of ToolbarTestItems.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type ToolbarTestItems was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<ToolbarTestItems> Items => _items ??= _item.Children<ToolbarTestItems>("Items");
    private IEnumerable<ToolbarTestItems> _items;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");
  }
}