// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ViewTestPresentation.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ViewTestPresentation
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.01
// App/Edition: App Test Features/
// User:        2sichost
// When:        2024-02-29 21:35:48Z
namespace AppCode.Data
{
  // This is a generated class for ViewTestPresentation
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ViewTestPresentation data. <br/>
  /// Generated 2024-02-29 21:35:48Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Emphasize`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ViewTestPresentation: ViewTestPresentationAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for ViewTestPresentation.
  /// </summary>
  public abstract class ViewTestPresentationAutoGenerated: Custom.Data.CustomItem
  {
    /// <summary>
    /// Emphasize as bool. <br/>
    /// To get nullable use .Get("Emphasize") as bool?;
    /// </summary>
    public bool Emphasize => _item.Bool("Emphasize");
  }
}