// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ViewSettingsDummyModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ViewSettingsDummyModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for ViewSettingsDummy (scope: System.Configuration)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ViewSettingsDummy custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.SomeNumber`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.Configuration.
  /// </remarks>
  public partial class ViewSettingsDummyModel: AutoGenerated.ZAutoGenViewSettingsDummyModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for System.Configuration.ViewSettingsDummyModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenViewSettingsDummyModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// SomeNumber as int. <br/>
    /// To get other types use methods such as .Decimal("SomeNumber")
    /// </summary>
    public int SomeNumber => _item.Int("SomeNumber");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}