// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "WithGPS.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class WithGPS
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
using ToSic.Sxc.Cms.Data;

namespace AppCode.Data
{
  // This is a generated class for WithGPS 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// WithGPS data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.GPS`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class WithGPS: AutoGenerated.ZAutoGenWithGPS
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.WithGPS in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenWithGPS: Custom.Data.CustomItem
  {
    /// <summary>
    /// GPS as GPS Coordinates object with Latitude and Longitude.
    /// </summary>
    public GpsCoordinates GPS => _item.Gps("GPS");

    /// <summary>
    /// GPSLat as int. <br/>
    /// To get other types use methods such as .Decimal("GPSLat")
    /// </summary>
    public int GPSLat => _item.Int("GPSLat");

    /// <summary>
    /// GPSLong as int. <br/>
    /// To get other types use methods such as .Decimal("GPSLong")
    /// </summary>
    public int GPSLong => _item.Int("GPSLong");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}