// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "WithMetadataMetadataModel.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class WithMetadataMetadataModel
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Test Features/
// User:        2sichost
namespace AppCode.Data
{
  // This is a generated custom model class for WithMetadataMetadata 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// WithMetadataMetadata custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Age`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  public partial class WithMetadataMetadataModel: AutoGenerated.ZAutoGenWithMetadataMetadataModel
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.WithMetadataMetadataModel in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenWithMetadataMetadataModel: Custom.Data.CustomModel
  {
    /// <summary>
    /// Age as int. <br/>
    /// To get other types use methods such as .Decimal("Age")
    /// </summary>
    public int Age => _item.Int("Age");

    /// <summary>
    /// Color as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Color", scrubHtml: true) etc.
    /// </summary>
    public string Color => _item.String("Color", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => _item.String("Title", fallback: "");
  }
}